print('┌─────────────────────────────┐                CONTROLS')
print('│                             │')
print('│       ██╗  ██╗████████╗     │   ┌─────┐                 ┌───┐')
print('│       ██║  ██║██╔██═██║     │   │ LMB │ Select points   │ C │   Crop mode')
print('│       ███████║██║██ ██║     │   └─────┘                 └───┘')
print('│       ██╔══██║██║   ██║     │   ┌─────┐                 ┌───┐')
print('│       ██║  ██║██║   ██║     │   │ RMB │ Drag map        │ Q │   Re-center map')
print('│       ╚═╝  ╚═╝╚═╝   ╚═╝     │   └─────┘                 └───┘')
print('│                             │   ┌─────┐                 ┌───┐')
print('│       Lunar Hazard Map      │   │ ESC │ Exit / Back     │ E │   Take screenshot ')
print('└─────────────────────────────┘   └─────┘                 └───┘')
print()